### PR TITLE
Make scraper scrape all worlds by clicking next page button

### PR DESCRIPTION
**Pull request by PilkeySEK**
also changed gradle.properties to allow for older clients to also use the mod cuz i had issues with it

### CODE REVIEW

**Comment by OmriPH** [comment]
bro did NOT resolve them conflicts

**Comment by OmriPH** [comment]
just merge master into your branch

**Comment by PilkeySEK** [comment]
i appear to have cooked my local repo can you do it :3

**Comment by OmriPH** [comment]
> i appear to have cooked my local repo can you do it :3

uhhhh





no :3

**Comment by OmriPH** [comment]
i have no idea how to solve conflicts :sob:

**Comment by PilkeySEK** [comment]
should b fixed

**Comment by OmriPH** [comment]
k
will merge

**Review by OmriPH — APPROVED** [review]

**Comment by OmriPH** [comment]
uh
i cant merge since i made a commit :skob:

**Pull request merged**
