### PR TITLE
Make scraper log less (configurable with a config option now)

### PR DESCRIPTION
**Pull request by PilkeySEK**
its really getting spammed with json data of the items

### CODE REVIEW

**Comment by OmriPH** [comment]
created world and updated world are NOT verbose they should be logged either way

**Comment by PilkeySEK** [comment]
you can change it back by committing to branch

**Comment by OmriPH** [comment]
> you can change it back by committing to branch

I can't review the pr if I have a commit on the branch

**Comment by PilkeySEK** [comment]
ok ill do

**Review by OmriPH — APPROVED** [review]

**Pull request merged**
